// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGllOqzNuaKioldKzkheppk4Un7sJMPl4',
    appId: '1:1066723358957:web:c3c2e56d59a0c5a1f374e4',
    messagingSenderId: '1066723358957',
    projectId: 'expensesapp-27e32',
    authDomain: 'expensesapp-27e32.firebaseapp.com',
    storageBucket: 'expensesapp-27e32.appspot.com',
    measurementId: 'G-9GCJ9Y7REP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNf_ho3kLrNc34Ftwbrl5HT-QdIglUWzQ',
    appId: '1:1066723358957:android:5063b6cdff45383af374e4',
    messagingSenderId: '1066723358957',
    projectId: 'expensesapp-27e32',
    storageBucket: 'expensesapp-27e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvgVDDWrt0cOUv-AoYwgLcgzv_fx9LLI',
    appId: '1:1066723358957:ios:40a2e3a42fc429e8f374e4',
    messagingSenderId: '1066723358957',
    projectId: 'expensesapp-27e32',
    storageBucket: 'expensesapp-27e32.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvgVDDWrt0cOUv-AoYwgLcgzv_fx9LLI',
    appId: '1:1066723358957:ios:40a2e3a42fc429e8f374e4',
    messagingSenderId: '1066723358957',
    projectId: 'expensesapp-27e32',
    storageBucket: 'expensesapp-27e32.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGllOqzNuaKioldKzkheppk4Un7sJMPl4',
    appId: '1:1066723358957:web:c1acad853e56b37bf374e4',
    messagingSenderId: '1066723358957',
    projectId: 'expensesapp-27e32',
    authDomain: 'expensesapp-27e32.firebaseapp.com',
    storageBucket: 'expensesapp-27e32.appspot.com',
    measurementId: 'G-4C4ZPF602J',
  );

}